version: '3.3'
services:
  dyndns-to-hetzner:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./config.py:/app/instance/config.py